import type { Project } from '@section/project/Project'

const projects: Project[] = [
  {
    name: 'arte',
    logo: 'arte',
    logoType: 'svg',
    color: '#fd4600',
    skills: [
      'React',
      'Next',
      'Typescript',
      'Javascript',
      'PHP',
      'Symfony',
      'Redis',
      'mySQL',
      'Storybook',
      'Eslint',
      'PHPUnit',
      'Github',
      'Docker',
      'Jest',
      'Web',
      'Git',
    ],
    companies: [
      'freelancer',
    ],
    url: 'https://arte.tv',
    images: [
      'arte/1.png',
      'arte/2.png',
      'arte/3.png',
      'arte/4.png',
    ],
    description_project: 'ARTE is a responsible European public media dedicated to issues that matter to European citizens: fighting inequalities—social, cultural, economic, geographic, gender, or disability-related—and promoting sustainable development.',
    description_mission: [
      'Redesigned the frontend of <a href=\'https://my.arte.tv\' target=\'_blank\'>my.arte.tv</a> as a component library',
      'Developed and optimized the user API (viewing history, content suggestions, account management), handling over 3 million requests per day',
      'Migrated ARTE\'s authentication system (IAM, OPENID) from LoginRadius to Keycloak',
      'Contributed to content caching strategies, database and system design, and code quality improvements',
      'Optimized the video player used on <a href=\'https://arte.tv\' target=\'_blank\'>arte.tv</a>',
      'Supported an external team in the migration of the user API to Symfony',
    ],
    recommendations: [],
    start: '2020-08-01',
    end: '2022-04-01',
  },
  {
    name: 'pfizer',
    logo: 'centaur',
    logoType: 'svg',
    color: '#2294fa',
    skills: [
      'Typescript',
      'Javascript',
      'NodeJS',
      'React',
      'AWS',
      'neo4j',
      'mySQL',
      'Docker',
      'Github',
      'Jenkins',
      'Eslint',
      'Jest',
      'Web',
      'Git',
    ],
    companies: [
      'freelancer',
    ],
    images: [
    ],
    description_project: 'Pfizer is a global leader in the pharmaceutical industry.\n\nDesigned and developed a cutting-edge platform to facilitate the setup and monitoring of clinical trials worldwide, leveraging AI-driven analysis, data consolidation, and advanced data visualization.',
    description_mission: [
      'Built advanced modules to support users\' day-to-day decision-making',
      'Redesigned the cloud architecture to enhance platform reliability and performance',
      'Optimized databases (normalization, indexing, etc.) for improved efficiency',
      'Implemented DevOps tools (monitoring, alerting, dashboards) to reduce error rates and accelerate incident resolution',
      'Created "Simple Search", an AI-powered search engine enabling users to access key data from multiple sources through natural language queries',
      'Conducted a technical audit, then reduced technical debt and improved code quality, readability, and architecture',
      'Redesigned and enhanced multiple user interfaces to improve usability',
    ],
    recommendations: [],
    start: '2022-04-01',
    end: '2023-12-23',
  },
  {
    name: 'Louis Vuitton',
    logo: 'louis-vuitton',
    logoType: 'svg',
    color: '#2C1B10',
    skills: [
      'Typescript',
      'Javascript',
      'NodeJS',
      'Nest',
      'Postgresql',
      'Docker',
      'Github',
      'Heroku',
      'Eslint',
      'Jest',
      'Web',
      'Git',
      'GCP',
      'Redis',
    ],
    companies: [
      'freelancer',
    ],
    images: [
    ],
    description_project: 'Louis Vuitton is an iconic French luxury house.\nDeveloped a Backend-for-Frontend API within a microservices architecture, powering the brand\'s mobile e-commerce applications and handling over 3 million requests per day.',
    description_mission: [
      'Developed “Store mode”, delivering a unique in-store experience via QR Code scanning',
      'Implemented a virtual waiting room system to handle traffic surges during major marketing events (product launches, drops, etc.)',
      'Built advanced features for product pages, including content suggestions and intelligent product search',
      'Led technical refactoring to improve maintainability and testability',
      'Implemented DevOps solutions (caching, rate-limiting, feature-flagging, Dockerization) for seamless integration into a microservices architecture',
      'Migrated the project from Heroku to Google Cloud Platform (GCP)',
    ],
    recommendations: [],
    start: '2024-02-12',
    end: '2025-06-30',
  },
  {
    name: 'Glooko',
    logo: 'glooko',
    logoType: 'svg',
    color: '#3D8AC9',
    skills: [
      'Typescript',
      'Javascript',
      'NodeJS',
      'React',
      'Express',
      'Postgresql',
      'Docker',
      'Github',
      'GCP',
      'Eslint',
      'Jest',
      'Web',
      'Git',
    ],
    companies: [
      'freelancer',
    ],
    images: [],
    description_project: 'Glooko XT is a digital remote monitoring solution designed for diabetes management. It automatically centralizes data from various medical devices, including blood glucose meters, continuous glucose monitors, insulin pumps, and connected insulin pens. The platform enables patients to monitor their data and share it with their healthcare team, while providing healthcare professionals with tools for remote analysis and monitoring. The solution relies on an interconnected software architecture to securely collect, centralize, and present healthcare data.',
    description_mission: [
      'Built a patient education module in which clinicians create care pathways from documents and videos, assign them to an entire group of patients in a single action, and track each patient\'s progress',
      'Redesigned the internal tool used by support agents to manage patient and healthcare professional accounts, enabling agents to resolve customer requests on their own',
      'Redesigned the platform\'s OAuth2 authentication flows (login, password reset, etc.), complemented by an audit trail of sensitive actions on professional accounts, to secure access to medical data and meet compliance requirements',
      'Made the codebase AI-ready by refactoring it and setting up agent instructions, skills, and automated code reviews',
      'Fixed security vulnerabilities, set up OpenAPI documentation, enforced validation of all incoming data, and added logging of sensitive actions',
    ],
    recommendations: [],
    start: '2026-02-23',
  },
  {
    name: 'coinbasket',
    logo: 'coinbasket',
    logoType: 'svg',
    color: '#f98500',
    skills: [
      'Typescript',
      'Javascript',
      'React',
      'Next',
      'Python',
      'Postgresql',
      'Docker',
      'Github',
      'Eslint',
      'Web',
      'Web 3',
      'Git',
    ],
    companies: [
      'freelancer',
    ],
    images: [
      'coinbasket/coinbasket_0.png',
      'coinbasket/coinbasket_1.png',
      'coinbasket/coinbasket_2.png',
      'coinbasket/coinbasket_3.png',
      'coinbasket/coinbasket_4.png',
    ],
    description_project: 'Winner of the ASI Alliance x BNB AI Hackathon, Coinbasket is an AI-powered crypto portfolio manager designed to simplify and personalize digital asset investing. By combining natural language processing and real-time market data, Coinbasket enables users to create and manage asset portfolios with a single prompt.',
    description_mission: [
      'Full-stack development of the platform, covering both front-end and back-end',
      'Engineered wallet management and on-chain interaction systems',
      'LLM and MCP integration',
      'Integration of web3 components such as web3.py, rainbowkit, 0x Protocol SWAP API',
    ],
    recommendations: [],
    start: '2025-05-01',
    end: '2026-12-31',
    url: 'https://coinbasket.ai',
  },
  {
    name: 'sunshare',
    logo: 'sunshare',
    logoType: 'svg',
    color: '#332a41',
    skills: [
      'Typescript',
      'Javascript',
      'React',
      'AWS',
      'Redis',
      'Bun',
      'Docker',
      'Github',
      'Eslint',
      'Web',
      'Web 3',
      'Git',
    ],
    companies: [
      'freelancer',
    ],
    images: [
      'sunshare/sunshare_1.png',
      'sunshare/sunshare_2.png',
      'sunshare/sunshare_3.png',
      'sunshare/sunshare_4.png',
      'sunshare/sunshare_5.png',
    ],
    description_project: 'Winner of TRON Hackathon Season 7, Sunshare is a secure, time-limited file sharing platform with transparent, pay-as-you-go pricing. Built on BTFS decentralized storage and zero-knowledge end-to-end encryption, it guarantees privacy and distributed storage. Pricing is managed by a public smart contract, offering a verifiable and transparent alternative to centralized solutions.',
    description_mission: [
      'End-to-end development of the platform, including front-end, back-end, and smart contracts',
      'Designed a zero-knowledge end-to-end encryption system',
      'Deployed the platform on AWS using Infrastructure as Code and CI/CD pipelines',
    ],
    recommendations: [],
    start: '2024-08-01',
    end: '2025-12-31',
    url: 'https://sunsha.re',
  },
  {
    name: 'kwote',
    logo: 'kwote',
    logoType: 'svg',
    color: '#987654',
    skills: [
      'Typescript',
      'Javascript',
      'NodeJS',
      'mySQL',
      'Redis',
      'Angular',
      'Eslint',
      'Gitlab',
      'Jenkins',
      'Web',
      'Git',
    ],
    companies: [
      'freelancer',
    ],
    url: 'https://kwote.fr',
    images: [
      'kwote/kwote_1.jpg',
      'kwote/kwote_2.jpg',
      'kwote/kwote_3.jpg',
      'kwote/kwote_4.jpg',
      'kwote/kwote_6.jpg',
      'kwote/kwote_5.jpg',
    ],
    description_project: 'Kwote is a risk management platform for mid-sized companies and SMEs. By connecting to company information systems, it provides financial directors, credit managers, and executives with tools to manage customer risk and monitor credit insurance contract performance, along with innovative services such as disruptive financing, online debt collection, and payment behavior-based scoring.',
    description_mission: [
      'Developed "COLLECT", a module for automating unpaid invoice recovery, featuring scenario-based action planning (email, SMS, mail, etc.) and a template editor—processing over 10,000 actions monthly',
      'Refactored codebase to enhance testability, scalability, and maintainability',
      'Built a reporting module aggregating key client data',
      'Developed a collaborative workspace module',
      'Integrated various connectors to external APIs (Atradius, Euler Hermes)',
      'Upgraded Angular versions across the project',
    ],
    recommendations: [],
    start: '2018-08-01',
    end: '2021-10-01',
  },
  {
    name: 'Arkema',
    logo: 'arkema',
    logoType: 'svg',
    color: '#299d80',
    skills: [
      'AWS',
      'NodeJS',
      'Typescript',
      'Javascript',
      'Terraform',
      'Gitlab',
      'Eslint',
      'Jest',
      'Web',
      'Git',
      'Datadog',
    ],
    companies: [
      'freelancer',
    ],
    images: [
    ],
    description_project: 'Arkema is a global specialty chemicals group.\n\nDeveloped cloud ETL architectures to facilitate the exchange of strategic information between the group\'s applications worldwide.',
    description_mission: [
      'Developed and maintained "Magellan", a supply-chain project processing over 1 million messages per month',
      'Managed the project end-to-end, from gathering user requirements to technical decisions and implementation',
      'Contributed to the technical cloud architecture for the group\'s various data flows',
      'Implemented DevOps tools to monitor key indicators (success rates, processing times, etc.)',
    ],
    recommendations: [],
    start: '2023-05-22',
    end: '2023-08-04',
  },
  {
    name: 'MateMeUp',
    logo: 'matemeup',
    color: '#b01515',
    skills: [
      'Javascript',
      'NodeJS',
      'React',
      'Redis',
      'jQuery',
      'Laravel',
      'PHP',
      'mySQL',
      'Git',
      'Github',
      'Web',
      'Eslint',
    ],
    companies: [
      'freelancer',
    ],
    images: [
      'matemeup/matemeup_web_1.jpg',
      'matemeup/matemeup_web_2.jpg',
      'matemeup/matemeup_web_3.jpg',
      'matemeup/matemeup_web_4.jpg',
    ],
    description_project: '"The purpose of the matemeup.com website is to centralize the tools necessary for e-sport players and more generally for video game players, to facilitate the creation of links and meetings while promoting the related gaming sphere (broadcasters , casters, videographers, etc.)."',
    description_mission: [
      'Development of a player matching tool that includes a textual and vocal lobby system with the ability to create, modify and delete ones',
      'Development of a real-time chat',
      'Development of a newsfeed where users can publish text and images',
      'Design, development and deployment',
    ],
    recommendations: [
      1,
    ],
    start: '2017-10-01',
    end: '2018-01-01',
  },
  {
    name: 'MateMeUp Mobile',
    logo: 'matemeup',
    color: '#ec6464',
    skills: [
      'Android',
      'iOS',
      'Java',
      'Swift',
      'Git',
      'Github',
    ],
    companies: [
      'freelancer',
    ],
    images: [
      'matemeup-mobile/matemeup_mobile_1.jpg',
      'matemeup-mobile/matemeup_mobile_2.jpg',
      'matemeup-mobile/matemeup_mobile_3.jpg',
      'matemeup-mobile/matemeup_mobile_4.jpg',
      'matemeup-mobile/matemeup_mobile_5.jpg',
    ],
    description_project: '"The purpose of the matemeup.com website is to centralize the tools necessary for e-sport players and more generally for video game players, to facilitate the creation of links and meetings while promoting the related gaming sphere (broadcasters , casters, videographers, etc.)."',
    description_mission: [
      'Development of a newsfeed where users can publish text and images',
      'Development of a real-time chat',
      'Development of an authentication system',
      'Design, development and deployment of iOS and Android apps',
    ],
    recommendations: [
      1,
    ],
    start: '2018-02-01',
    end: '2018-08-01',
    isVisible: false,
  },
  {
    name: 'Cloudindus',
    logo: 'cloudindus',
    logoType: 'svg',
    color: '#dadadd',
    skills: [
      'Javascript',
      'NodeJS',
      'MongoDB',
      'Angular',
      'Web',
      'Git',
    ],
    companies: [
      'cloudindus',
    ],
    images: [
      'cloudindus/cloudindus_1.gif',
      'cloudindus/cloudindus_2.jpg',
      'cloudindus/cloudindus_3.jpg',
      'cloudindus/cloudindus_4.jpg',
      'cloudindus/cloudindus_5.png',
    ],
    description_project: 'Cloudindus is an industrial supervision platform enabling configuration and management of IoT devices. It allows both individuals and professionals to interact with and monitor the status of their connected devices, with user-defined interactions and visualizations through an intuitive interface.',
    description_mission: [
      'Engineered a system for recursively updating the state of connected devices based on the status of other networked objects',
      'Developed a graphical (SVG) visualization system for device status',
      'Developed the user authentication (OPENID) and authorization (OAUTH2) module',
      'Enabled application internationalization',
      'Led the design, development, and deployment of the platform',
    ],
    recommendations: [],
    start: '2015-05-01',
    end: '2017-03-01',
  },
  {
    name: 'The Babel Community',
    logo: 'the-babel-community',
    color: '#000000',
    skills: [
      'Javascript',
      'jQuery',
      'PHP',
      'Symfony',
      'mySQL',
      'Web',
      'Git',
      'Laravel',
    ],
    companies: [
      'freelancer',
    ],
    url: 'https://thebabelcommunity.com/en',
    images: [
      'the-babel-community/the_babel_community_1.jpg',
      'the-babel-community/the_babel_community_2.jpg',
      'the-babel-community/the_babel_community_3.jpg',
      'the-babel-community/the_babel_community_4.jpg',
      'the-babel-community/the_babel_community_5.jpg',
      'the-babel-community/the_babel_community_6.jpg',
      'the-babel-community/the_babel_community_7.png',
      'the-babel-community/the_babel_community_8.png',
    ],
    description_project: 'The Babel Community is France\'s leading coworking and coliving residence brand.',
    description_mission: [
      'Established the digital presence of The Babel Community',
      'Developed and launched the brand\'s showcase website <a href="https://thebabelcommunity.com" target="_blank">The Babel Community</a>',
      'Built and deployed a web app for residents to interact with services such as restaurant reservations and sports class bookings',
    ],
    recommendations: [],
    start: '2018-10-01',
    end: '2019-02-01',
  },
  {
    name: 'The Babel Zone',
    logo: 'the-babel-zone',
    color: '#000000',
    skills: [
      'Javascript',
      'PHP',
      'Laravel',
      'mySQL',
      'Web',
      'PWA',
      'Git',
      'React',
    ],
    companies: [
      'freelancer',
    ],
    images: [
      'the-babel-zone/the_babel_zone_1.png',
      'the-babel-zone/the_babel_zone_2.png',
      'the-babel-zone/the_babel_zone_3.png',
      'the-babel-zone/the_babel_zone_4.png',
    ],
    description_project: 'The Babel Zone is a web app designed for residents, enabling them to interact with all services offered by the residence, from restaurant orders to sports class sign-ups and meeting room bookings.',
    description_mission: [
      'Developed the entire web app, enabling residents to order food, sign up for sports classes, and book meeting rooms',
      'Led the design, development, and deployment of the application',
    ],
    recommendations: [],
    start: '2018-08-01',
    end: '2019-05-01',
    isVisible: false,
  },
  {
    name: 'Album Quiz',
    logo: 'album-quiz',
    color: '#00d3ee',
    skills: [
      'React',
      'iOS',
      'Android',
      'AWS',
      'Git',
    ],
    companies: [
      'freelancer',
    ],
    url: 'https://play.google.com/store/apps/details?id=com.albumquiz&hl=fr',
    images: [
      'album-quiz/1.png',
      'album-quiz/2.png',
      'album-quiz/3.png',
      'album-quiz/4.png',
      'album-quiz/5.png',
      'album-quiz/6.png',
    ],
    description_project: 'Album Quiz | Rap Français is a music quiz game where players guess the artist from an album title. Focused on French urban music, it features over 3,500 albums spanning 30 years.',
    description_mission: [
      'Developed the game for Android and iOS',
      'Led the design, development, and launch of the game',
    ],
    recommendations: [],
    start: '2019-03-01',
    end: '2019-11-01',
  },
  {
    name: 'AXIS',
    logo: 'axis',
    color: '#FFFFFF',
    skills: [
      'Javascript',
      'jQuery',
      'PHP',
      'mySQL',
      'Web',
      'Git',
    ],
    companies: [
      'axis',
    ],
    images: [
      'intranet-axis/intra_1.jpg',
      'intranet-axis/intra_2.jpg',
      'intranet-axis/intra_3.jpg',
      'intranet-axis/intra_4.jpg',
      'intranet-axis/intra_5.jpg',
      'intranet-axis/intra_6.jpg',
    ],
    description_project: 'The AXIS Intranet is a custom tool used by AXIS Immobilier to centralize information.',
    description_mission: [
      'Redesigned the ERP\'s user interface',
      'Developed modules for invoicing, customer management, stock tracking, and accommodation reservations',
      'Implemented various enhancements to the ERP',
    ],
    recommendations: [],
    start: '2017-04-01',
    end: '2017-09-01',
  },
  {
    name: 'Foody Basket',
    logo: 'foody-basket',
    color: '#fd8600',
    skills: [
      'Lua',
      'Corona',
      'Android',
      'iOS',
      'Git',
    ],
    companies: [
      'freelancer',
    ],
    url: 'https://play.google.com/store/apps/details?id=fr.hotmail.meddegivet.FoodyBasket',
    images: [
      'foody-basket/in-game1.png',
      'foody-basket/league-fr.png',
      'foody-basket/menu-fr.png',
      'foody-basket/in-game2.png',
      'foody-basket/select-menu-fr.png',
    ],
    description_project: 'Foody Basket is a mobile basketball game featuring over a dozen customizable characters inspired by iconic fast food dishes. Multiple game modes are available, from single matches to full championships.',
    description_mission: [
      'Developed the game for Android, iOS, and Windows',
      'Managed the design, development, and release of the game',
    ],
    recommendations: [],
    start: '2016-09-01',
    end: '2017-04-01',
  },
  {
    name: 'The Babel Staff',
    logo: 'the-babel-staff',
    color: '#000000',
    skills: [
      'React',
      'Javascript',
      'PHP',
      'Laravel',
      'mySQL',
      'Web',
      'PWA',
      'Git',
    ],
    companies: [
      'freelancer',
    ],
    images: [
      'the-babel-staff/the_babel_staff_1.jpg',
      'the-babel-staff/the_babel_staff_2.jpg',
      'the-babel-staff/the_babel_staff_3.jpg',
      'the-babel-staff/the_babel_staff_4.jpg',
      'the-babel-staff/the_babel_staff_5.jpg',
    ],
    description_project: 'The Babel Staff is a web app for residence staff (servers, kitchen, housekeeping, etc.), enabling them to manage daily tasks in a ToDo format.',
    description_mission: [
      'Developed the entire web app for staff to manage daily tasks as ToDos',
      'Oversaw the design, development, and deployment of the application',
    ],
    recommendations: [],
    start: '2018-08-01',
    end: '2019-05-01',
    isVisible: false,
  },
  {
    name: 'Presta diagnostic',
    logo: 'prestadiagnostic',
    color: '#cfe7f8',
    skills: [
      'Javascript',
      'PHP',
      'mySQL',
      'Laravel',
      'jQuery',
      'PHPUnit',
      'Web',
      'Git',
    ],
    companies: [
      'freelancer',
    ],
    images: [
      'prestadiagnostic/prestadiagnostic_2.png',
      'prestadiagnostic/prestadiagnostic_1.png',
      'prestadiagnostic/prestadiagnostic_3.png',
    ],
    description_project: 'Prestadiagnostic is an online platform that connects users directly with nearby real estate diagnosticians.',
    description_mission: [
      'Developed a matching algorithm connecting users with real estate diagnosticians',
      'Created a property valuation algorithm',
      'Integrated Google Analytics',
      'Integrated Monetico payment module',
      'Led the design, development, and deployment of the platform',
    ],
    recommendations: [],
    start: '2020-06-01',
    end: '2021-07-01',
  },
  {
    name: 'Agora',
    logo: 'agora',
    color: '#f9f9f9',
    skills: [
      'Kotlin',
      'Android',
      'Git',
    ],
    companies: [
      'school',
    ],
    url: 'https://github.com/mehdidotcafe/Agora',
    images: [
      'agora/5.png',
      'agora/1.png',
      'agora/2.png',
      'agora/3.png',
      'agora/4.png',
    ],
    description_project: 'Agora is a web and mobile platform designed to connect people with complementary skills to foster new ideas. Users can form teams around their projects or join existing ones, with tools like retro-planning, storage, and task management to ensure smooth project execution.',
    description_mission: [
      'Developed the Android application',
      'Built OAUTH2 authentication and project search forms',
      'Developed project and user profile pages',
      'Managed the design, development, and deployment of the platform',
    ],
    recommendations: [],
    start: '2017-09-01',
    end: '2019-03-01',
    isVisible: false,
  },
  {
    name: 'Toocamp',
    logo: 'toocamp',
    color: '#0e4a68',
    skills: [
      'Javascript',
      'NodeJS',
      'mySQL',
      'Web',
      'Git',
    ],
    companies: [
      'freelancer',
    ],
    url: 'https://www.toocamp.com/',
    images: [
      'toocamp/toocamp_1.jpg',
      'toocamp/toocamp_2.jpg',
      'toocamp/toocamp_3.jpg',
      'toocamp/toocamp_4.jpg',
      'toocamp/toocamp_5.png',
    ],
    description_project: 'Toocamp is a content and services platform dedicated to camping holidays. Its mission is to make it easy for vacationers to search for and choose campsites, with curated content, promotional offers, a powerful search engine, and user reviews.',
    description_mission: [
      'Implemented website internationalization',
    ],
    recommendations: [],
    start: '2018-06-01',
    end: '2018-08-01',
    isVisible: false,
  },
  {
    name: 'Fivorites',
    logo: 'fivorites',
    color: '#FFFFFF',
    skills: [
      'Javascript',
      'NodeJS',
      'mySQL',
      'Web',
      'Git',
    ],
    companies: [
      'freelancer',
    ],
    images: [
      'fivorites/fivorites_1.jpg',
      'fivorites/fivorites_2.jpg',
      'fivorites/fivorites_3.jpg',
      'fivorites/fivorites_4.jpg',
    ],
    description_project: 'Fivorites lets you share your top 5 favorite movies, series, books, music, and comics with friends. Create your lists, share them, and discover what your friends love most.',
    description_mission: [
      'Developed scripts to acquire social network data (albums, series) from Deezer and iTunes APIs',
    ],
    recommendations: [],
    start: '2018-09-01',
    end: '2018-11-01',
    isVisible: false,
  },
  {
    name: 'The Colivers',
    logo: 'the-colivers',
    color: '#d75347',
    skills: [
      'Javascript',
      'PHP',
      'mySQL',
      'Web',
      'Git',
    ],
    companies: [
      'freelancer',
    ],
    url: 'https://thecolivers.com/',
    images: [
      'the-colivers/the-colivers_1.jpg',
      'the-colivers/the-colivers_2.jpg',
      'the-colivers/the-colivers_3.jpg',
      'the-colivers/the-colivers_4.jpg',
    ],
    description_project: 'THE COLIVERS is a rental agency specializing in shared apartments.',
    description_mission: [
      'Rebranded and redesigned the former L\'AUBERGE website for the new THE COLIVERS brand (<a href="https://thecolivers.com" target="_blank">THE COLIVERS</a>)',
      'Led the design, development, and deployment of the new website',
    ],
    recommendations: [],
    start: '2018-02-01',
    end: '2018-03-01',
    isVisible: false,
  },
  {
    name: 'DeezDL',
    logo: 'deezdl',
    color: '#1e2121',
    skills: [
      'Javascript',
      'Chrome',
      'Git',
      'Web',
    ],
    companies: [
      'freelancer',
    ],
    url: 'https://chrome.google.com/webstore/detail/deezdl/ojkgeljdeihmnoamceidbdlcfogjlmmg',
    images: [
      'deezdl/1.png',
      'deezdl/2.png',
    ],
    description_project: 'Developed a Google Chrome extension that enables users to download music from Deezer via an external site.',
    recommendations: [],
    isVisible: false,
    start: '2015-03-01',
    end: '2015-05-01',
  },
]

export default projects
